### ISSUE TITLE
genomic coordinates cannot align with the sequence in provided dataset

### ISSUE THREAD

**Issue by LoneKnightz** [zhangying-njust/CLSM6A#1]
Hi,

Thanks for providing this tool for m6a prediction. 

I am trying to learn this tool by training the model on prodvided dataset. 

But I found out the coordinates cannot align with the sequence in provided dataset (https://github.com/zhangying-njust/CLSM6A/tree/master/data_train_test)

for example, In A549_test, first sequence. I used BLAST and found out this sequence is from Homo sapiens chromosome 4, GRCh38.p14 Primary Assembly, + , 143556077 to 143556277 but given is chrY ,21618531.0 , -

Can you help with this ? Thanks

**Comment by zhangying-njust** [comment]
Thank you for your detailed observation. After reviewing the dataset, we have corrected the coordinates. (https://github.com/zhangying-njust/CLSM6A/tree/master/data_train_test).
Please note that the coordinates provided in the dataset represent the central positions of the sequences. Additionally, ensure that you are working with the GRCh37.p13 Primary Assembly.

**Comment by zhangying-njust** [comment]
Thank you for your detailed observation. After reviewing the dataset, we have corrected the coordinates. (https://github.com/zhangying-njust/CLSM6A/tree/master/data_train_test).
Please note that the coordinates provided in the dataset represent the central positions of the sequences. Additionally, ensure that you are working with the GRCh37.p13 Primary Assembly.
